In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns

split this string


In [2]:

s="Hi there Sam!"
x = s.split()

print(x)

['Hi', 'there', 'Sam!']


use.format() to print the following string

output should be: The deameter of Earth is 12742 kms.

In [3]:

planet="Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


IN  this nest dicftionary grab the word"hello"

In [ ]:
 
d= {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


create ab array of 10 zeros?

In [4]:

array=np.zeros(10)
print("An array of 10 zeros:")
print(array)




An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


create ab array of 10 fives?

In [5]:

array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


create an array of all the even integers from 20 to 35


In [6]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


create a 3*3 matrix with values ranging from 0 to 8


In [7]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


concatinate a and b

In [8]:

a=np.array([1,2,3])
b= np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]



create a data frame with 3 rows and 2 columns

In [9]:


data = [['sindhu', 21], ['yazhini', 20], ['vishal', 22]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df


Name  Age
0   sindhu   21
1  yazhini   20
2   vishal   22

generate the series of dates from 1st jan, 2023 to 10th feb, 2023

In [10]:

import datetime
pd.date_range(start="2023-01-01",end="2023-02-10").to_pydatetime().tolist()


[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2023, 1, 2, 0, 0),
 datetime.datetime(2023, 1, 3, 0, 0),
 datetime.datetime(2023, 1, 4, 0, 0),
 datetime.datetime(2023, 1, 5, 0, 0),
 datetime.datetime(2023, 1, 6, 0, 0),
 datetime.datetime(2023, 1, 7, 0, 0),
 datetime.datetime(2023, 1, 8, 0, 0),
 datetime.datetime(2023, 1, 9, 0, 0),
 datetime.datetime(2023, 1, 10, 0, 0),
 datetime.datetime(2023, 1, 11, 0, 0),
 datetime.datetime(2023, 1, 12, 0, 0),
 datetime.datetime(2023, 1, 13, 0, 0),
 datetime.datetime(2023, 1, 14, 0, 0),
 datetime.datetime(2023, 1, 15, 0, 0),
 datetime.datetime(2023, 1, 16, 0, 0),
 datetime.datetime(2023, 1, 17, 0, 0),
 datetime.datetime(2023, 1, 18, 0, 0),
 datetime.datetime(2023, 1, 19, 0, 0),
 datetime.datetime(2023, 1, 20, 0, 0),
 datetime.datetime(2023, 1, 21, 0, 0),
 datetime.datetime(2023, 1, 22, 0, 0),
 datetime.datetime(2023, 1, 23, 0, 0),
 datetime.datetime(2023, 1, 24, 0, 0),
 datetime.datetime(2023, 1, 25, 0, 0),
 datetime.datetime(2023, 1, 26, 0,

create 2D list to dataframe

In [11]:

lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df = pd.DataFrame(lists, columns =['Id', 'Name','Age']) 
print(df )

   Id Name  Age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24
